name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: "Set up Python 3.13.2"
      uses: actions/setup-python@v3
      with:
        python-version: "3.13.2"
    - name: Unit test
      run: |
        python3 test.py
    - uses: DeterminateSystems/nix-installer-action@main
    - name: Integration test
      run: |
        ./mill_ivy_fetcher.py --help
        exe=$(realpath ./mill_ivy_fetcher.py)
        git clone --depth=1 https://github.com/chipsalliance/chisel.git
        pushd chisel >/dev/null
        javaHome=$(mktemp -d)
        "$exe" fetch --home "$javaHome" --targets "unipublish"
        nvfetchKey=$(mktemp)
        "$exe" dump --coursier-dir "$javaHome/.cache/coursier" --dump-path "$nvfetcherKey"
        nix run '.#nvfetcher' -- -k "$nvfetcherKey"
