name: Test

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]
        types: ["opened", "synchronize", "reopened", "ready_for_review"]

permissions:
    contents: read

jobs:
    format-check:
        if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: DeterminateSystems/nix-installer-action@main
            - name: Check formatting
              run: nix fmt -- --ci

    gen-build-matrix:
        if: github.event_name == 'pull_request' && github.event.pull_request.draft == false
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{ steps.set-matrix.outputs.matrix }}
        steps:
            - uses: actions/checkout@v4
            - uses: DeterminateSystems/nix-installer-action@main
            - name: "Set Matrix"
              id: set-matrix
              run: |
                  nix eval --json ".#millVersions.allVersions" | nix run '.#jq' -- -rc '"matrix=" + ({version: .} | tostring)' > "$GITHUB_OUTPUT"

    build-mill-versions:
        if: github.event_name == 'pull_request' && github.event.pull_request.draft == false
        needs: [gen-build-matrix]
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix: ${{ fromJSON(needs.gen-build-matrix.outputs.matrix) }}
        steps:
            - uses: actions/checkout@v4
            - uses: DeterminateSystems/nix-installer-action@main
            - run: |
                  nix build '.#millVersions.${{ matrix.version }}'
                  result/bin/mill --version
