name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  gen-build-matrix:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - name: "Set Matrix"
      id: set-matrix
      run: |
        nix eval --json ".#millVersions.allVersions" | nix run '.#jq' -- -rc '"matrix=" + ({version: .} | tostring)' > "$GITHUB_OUTPUT"

  build-mill-versions:
    needs: [gen-build-matrix]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.gen-build-matrix.outputs.matrix) }}
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - run: |
        nix build '.#millVersions.${{ matrix.version }}'
        result/bin/mill --version

  integration-test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - name: Integration test
      run: |
        nix build '.#ci-test' --max-jobs auto
